Set default values in settings to avoid errors
```
File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for Cinema4DSettings
imageio -> render
field required (type=value_error.missing)
imageio -> display
field required (type=value_error.missing)
imageio -> view
field required (type=value_error.missing)
imageio -> thumbnails
field required (type=value_error.missing)
```